# Generated by Django 5.0.2 on 2024-02-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('occupy', models.CharField(max_length=100)),
                ('type_of_trial', models.CharField(choices=[('-', 'Empty'), ('CMJ', 'Cmj'), ('SJ', 'Sj'), ('ISO', 'Iso'), ('DJ', 'Dj')], default='-', max_length=10)),
                ('drop_jump_height', models.FloatField(blank=True, null=True)),
                ('filename', models.CharField(max_length=200)),
                ('filepath', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
