# Generated by Django 5.0.2 on 2024-02-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpmetric', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trial',
            options={'ordering': ['id']},
        ),
    ]
