# Generated by Django 5.0.2 on 2024-02-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpmetric', '0002_alter_trial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='trial_csv',
            field=models.FileField(null=True, upload_to='trials_csv/% Y/% m/% d/'),
        ),
    ]
