# Generated by Django 5.0.2 on 2024-02-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpmetric', '0003_trial_trial_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='trial_csv',
            field=models.FileField(blank=True, null=True, upload_to='trials_csv/% Y/% m/% d/'),
        ),
    ]
