# Generated by Django 5.0.2 on 2024-02-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpmetric', '0005_alter_trial_age_alter_trial_email_alter_trial_occupy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
