# Generated by Django 5.0.2 on 2024-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpmetric', '0013_alter_trial_trial_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='filepath',
        ),
        migrations.AlterField(
            model_name='trial',
            name='trial_csv',
            field=models.FileField(blank=True, null=True, upload_to='trials_csv'),
        ),
    ]
