# Generated by Django 5.0.2 on 2024-02-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpmetric', '0014_remove_trial_filepath_alter_trial_trial_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
