# Generated by Django 5.0.2 on 2024-02-12 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpmetric', '0015_alter_trial_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DateTimeField(default=datetime.datetime.now)),
                ('y', models.IntegerField()),
            ],
        ),
    ]
