# Generated by Django 5.0.2 on 2024-02-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumpmetric', '0016_datapoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPoint',
        ),
    ]
