# Generated by Django 5.0.2 on 2024-02-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpmetric', '0017_delete_datapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='trial_csv',
            field=models.FileField(upload_to='trials_csv'),
        ),
    ]
