# Generated by Django 5.0.2 on 2024-02-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumpmetric', '0018_alter_trial_trial_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trial',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trial',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trial',
            name='weight',
            field=models.FloatField(),
        ),
    ]
